#pragma once

#define WINDOW_W 1500
#define WINDOW_H 780

#define BLOCK_W 175
#define BLOCK_H 55

#define NUM_DAY_WORKDAY 5
#define NUM_DAY_WEEKEND 2

#define NUM_CLASS_MORN 5
#define NUM_CLASS_NOON 5
#define NUM_CLASS_DUSK 3

#define NUM_DAY (NUM_DAY_WORKDAY+NUM_DAY_WEEKEND)
#define NUM_CLASS (NUM_CLASS_MORN+NUM_CLASS_NOON+NUM_CLASS_DUSK)
